services:
  website:
    image: transgressoft-website:latest
    build: .
    container_name: transgressoft-website
    ports:
      - "3001:3001"
    env_file:
      - .env
    restart: unless-stopped
